### ISSUE TITLE
Firefox 44 support

### ISSUE THREAD

**Issue by edouard-lopez** [Boboseb/colorblind-design#1]
The addon is broken on the [Firefox Developer Edition](https://www.mozilla.org/en-US/firefox/developer/) `44`. 

This might be due to Electrolysis.

**Comment by Boboseb** [comment]
I think [bug 912121](https://bugzilla.mozilla.org/show_bug.cgi?id=912121) is also a problem for this addon.

**Comment by Boboseb** [comment]
I think this line
Cu.import("resource:///modules/devtools/responsivedesign.jsm");
should be replaced by
Cu.import('resource://devtools/client/responsivedesign/responsivedesign.jsm');
for Firefox 44+
